[versions]
detekt = "1.22.0"
# Use -beta for pre-releases
detektIJ = "2.0.0-beta"
assertj = "3.24.2"
junit5 = "5.9.2"

[libraries]
detekt-core = { group = "io.gitlab.arturbosch.detekt", name = "detekt-core", version.ref = "detekt" }
detekt-api = { group = "io.gitlab.arturbosch.detekt", name = "detekt-api", version.ref = "detekt" }
detekt-rules = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-tooling = { group = "io.gitlab.arturbosch.detekt", name = "detekt-tooling", version.ref = "detekt" }
detekt-testUtils = { group = "io.gitlab.arturbosch.detekt", name = "detekt-test-utils", version.ref = "detekt" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "junit5" }

[plugins]
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.8.20"
versions = "com.github.ben-manes.versions:0.46.0"
intellij = "org.jetbrains.intellij:1.13.3"
github-release = "com.github.breadmoirai.github-release:2.4.1"
